language: python
env:
  - PYTHON_VERSION=3.7 TENSORFLOW_VERSION=2.4.0

before_install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - sh Miniconda3-latest-Linux-x86_64.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict

install:
  - conda env create --file environment.yml
  - source activate test
script:
  - python -m pytest .
  - python -u train_mode_cnn.py config/ws_mode_cnn_train_small.yml -t -i -p
notifications:
  email: true
