name: hwtmode
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - pyyaml
  - netcdf4
  - scikit-learn
  - seaborn
  - pyproj
  - cartopy
  - tqdm
  - memory_profiler
  - scikit-image
  - pyarrow
  - s3fs
  - joblib
  - flake8
  - jupyterlab
  - ipywidgets
  - pip:
    - basemap
    - tensorflow
    - tensorflow-probability
    - pytest
    - geopandas
    - regionmask
