data_path: "/glade/scratch/cbecker/HRRR_objects/HRRR_AWS_realtime_test_20211005/track_data_hrrr_3km_nc_refl/"
csv_model_prefix: "track_step_HRRR-ZARR_oper_"
meta_variables: ["masks", "i", "j", "lon", "lat", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
agg_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_max"]
physical_model: "HRRR" # patch data type derived from "data_path"
storm_report_path: "/glade/work/cbecker/SPC_storm_reports/"
model_grid_path: '/glade/work/cbecker/HWT_mode/model_grids/NCEP_211_grid.nc'
run_start_date: "2016-01-01"
run_end_date: "2016-12-31"
run_freq: "daily"
output_format: "parquet"
models:
  semi_supervised:
    mod_0:
      model_path: "/glade/scratch/cbecker/HWT_20211110_REFL/"
      patch_radius: 32
      input_variables: ["REFC-entire_atmosphere_curr"]
      output_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
  supervised:
    cnn_test_000:
      model_path: "/glade/scratch/cbecker/HWT_supervised/"
      patch_radius: 32
      input_variables: ["REFC-entire_atmosphere_curr", "MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
      output_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
