data_path: "/glade/scratch/cbecker/HRRR_objects/20220228/201905_201906_daily/track_data_hrrr_3km_nc/"
csv_model_prefix: "track_step_HRRR-ZARR_oper_"
patch_meta_variables: ["masks", "i", "j", "lon", "lat", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
csv_meta_variables: ['Valid_Date', 'Run_Date', 'Forecast_Hour', 'Step_ID', 'Track_ID',
                      'Duration', 'Centroid_Lon', 'Centroid_Lat']
storm_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_max",
                "VUCSH-0_6000m_above_ground-potential_mean",
                "VVCSH-0_6000m_above_ground-potential_mean"]
#                "CAPE-0_3000m_above_ground_potential_max", # only in v4
#                "CAPE-0_3000m_above_ground_potential_mean"]
physical_model: "HRRR" # patch data type derived from "data_path"
storm_report_path: "/glade/work/cbecker/SPC_storm_reports/"
model_grid_path: '/glade/work/cbecker/HWT_mode/model_grids/NCEP_211_grid.nc'
run_start_date: "2019-05-01"
run_end_date: "2019-06-01"
run_freq: "daily"
output_format: "parquet"
bin_width: null # ML probability bins
proj_str: "+proj=lcc +lat_0=38.5 +lon_0=-97.5 +lat_1=38.5 +lat_2=38.5 +a=6371229 +b=6371229"
models:
  semi_supervised:
    CNN_1:
      model_path: "/glade/scratch/cbecker/HWT_20220111_REFLUH_copy2/"
      patch_radius: 32
      input_variables: ["REFC-entire_atmosphere_curr", "MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
      output_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
  supervised:
    cnn_test_000:
      model_path: "/glade/scratch/cbecker/HWT_supervised_copy/"
      patch_radius: 32
      input_variables: ["REFC-entire_atmosphere_curr", "MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
      output_variables: ["MXUPHL_1hr_max_fcst-5000_2000m_above_ground_curr"]
  supervised_DNN:
    DNN_1:
      model_path: "/glade/scratch/cbecker/HWT_DNN"
      input_variables: [ "Centroid_Lat",
                         "MXUPHL_1hr_max_fcst-5000_2000m_above_ground_max",
                         "Forecast_Hour",
                         "major_axis_length",
                         "HGT-level_of_adiabatic_condensation_from_sfc_max",
                         "Centroid_Lon",
                         "USTM-0_6000m_above_ground_min",
                         "eccentricity",
                         "MAXUVV_1hr_max_fcst-100_1000mb_above_ground_mean",
                         "TCOLG_1hr_max_fcst-entire_atmosphere_single_layer_mean" ]
