data_path: "/glade/scratch/cbecker/MPAS_interp_HRRR/track_data_MPAS_interp_hrrr_3km_nc_refl/"
csv_data_path: "/glade/scratch/cbecker/MPAS_interp_HRRR/track_data_MPAS_interp_hrrr_3km_csv_refl/"
csv_model_prefix: "track_step_MPAS-interp_1_"
json_prefix: "MPAS-interp_1_"
use_full_obj: True
patch_meta_variables: ["masks", "i", "j", "lon", "lat", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
csv_meta_variables: ['Valid_Date', 'Run_Date', 'Forecast_Hour', 'Step_ID', 'Track_ID',
                      'Duration', 'Centroid_Lon', 'Centroid_Lat']
storm_variables: ["updraft_helicity_max03_mean"]
model_grid_path: '/glade/work/cbecker/HWT_mode/model_grids/NCEP_211_grid.nc'
run_start_date: "2023-04-24"
run_end_date: "2023-05-31"
run_freq: "daily"
output_format: "parquet"
output_path: "/glade/scratch/cbecker/MPAS_interp_HRRR/model_output/mem_1/"
proj_str: "+proj=lcc +lat_0=38.5 +lon_0=262.5 +lat_1=38.5 +lat_2=38.5 +a=6371229 +b=6371229"
models:
  semi_supervised:
    SS:
      model_path: "/glade/work/cbecker/HWT/HWT_models/HWT_20220318_SS/"
      gmm_name: 'GMM'
      label_dict: 'SS_GMM_labels_charlie_2022-03-22_1636.dict'
      patch_radius: 32
      input_variables: ["refl10cm_max_curr", "updraft_helicity_max03_curr"]
      output_variables: ["updraft_helicity_max03_curr"]
  supervised:
    CNN_1:
      model_path: "/glade/work/cbecker/HWT/HWT_models/HWT_CNN/"
      patch_radius: 32
      input_variables: ["refl10cm_max_curr", "updraft_helicity_max03_curr"]
      output_variables: ["updraft_helicity_max03_curr"]
#  supervised_DNN:
#    DNN_1:
#      model_path: "/glade/work/cbecker/HWT/HWT_models/HWT_DNN/"
#      input_variables: [ "Centroid_Lat",
#                         "MXUPHL_1hr_max_fcst-5000_2000m_above_ground_max",
#                         "Forecast_Hour",
#                         "major_axis_length",
#                         "HGT-level_of_adiabatic_condensation_from_sfc-potential_max",
#                         "Centroid_Lon",
#                         "USTM-0_6000m_above_ground-potential_min",
#                         "eccentricity",
#                         "MAXUVV_1hr_max_fcst-100_1000mb_above_ground_mean",
#                         "TCOLG_1hr_max_fcst-entire_atmosphere_single_layer_mean" ]
