data_path: "/glade/scratch/cbecker/NSC_data/track_data_nsc_3km_REFL_COM_ws_nc/"
patch_radius: 16
input_variables: ["REFL_COM_curr"]
output_variables: ["UP_HELI_MAX_future"]
meta_variables: ["masks", "i", "j", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
# Use 'SHR6_prev' to calculate 6km shear magnitude from the U and V components
train_start_date: "2010-10-01"
train_end_date: "2011-12-31"
val_start_date: "2016-01-01"
val_end_date: "2016-12-31"
test_start_date: "2017-01-01"
test_end_date: "2017-06-30"
out_path: "/glade/scratch/cbecker/HWT_out/refl_uh_class_20211019/"
classifier: 1
classifier_threshold: 50
plot_kwargs:
  REFL_COM_curr:
    vmin: 0
    vmax: 80
    cmap: "gist_ncar"
  MLCAPE_prev:
    vmin: 0
    vmax: 5000
    cmap: "plasma"
  SHR6_prev:
    vmin: 0
    vmax: 100
    cmap: "viridis"

models:
  mod_0:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 1.5
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 0
    dropout_alpha: 0.2
    epochs: 30
    dense_neurons: 6
    covariance_scale: 1000
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
  mod_1:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 1.5
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "max"
    loss: "binary_crossentropy"
    hidden_activation: "leaky"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 0
    dropout_alpha: 0.2
    epochs: 30
    dense_neurons: 6
    covariance_scale: 1000
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1

GMM_models:
  GMM_0:
    n_components: 7
    covariance_type: 'full'
    max_iter: 1000
    tol: 0.001
    n_init: 5
    init_params: 'kmeans'
    reg_covar: 0.000001
    verbose: 1
  GMM_1:
    n_components: 4
    covariance_type: 'full'
    max_iter: 1000
    tol: 0.001
    n_init: 5
    init_params: 'kmeans'
    reg_covar: 0.000001
    verbose: 1