data_path: "/glade/scratch/cbecker/WRF_objects/WRF_test_041421/track_data_wrf_3km_nc_refl/"
meta_variables: ["masks", "i", "j", "lon", "lat", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
run_start_date: "today"
run_end_date: "today"
run_freq: "daily"
out_path: "/glade/scratch/cbecker/HWT_rt_mods/"
activation_path: "/glade/scratch/cbecker/HWT_WRF_test_output/activations/"
labels_path: "/glade/scratch/cbecker/HWT_WRF_test_output/labels/"
models:
  semi_supervised:
    mod_0:
      patch_radius: 32
      input_variables: ["REFL_COM_curr"]
      output_variables: ["UP_HELI_MAX_curr"]
  supervised:
    cnn_test_000:
      patch_radius: 32
      input_variables: ["REFL_COM_curr", "UP_HELI_MAX_curr"]
      output_variables: ["UP_HELI_MAX_curr"]