data_path: "/glade/scratch/dgagne/NSC_data/track_data_nsc_3km_REFL_COM_ws_nc"
patch_radius: 16
input_variables: ["REFL_COM_curr"]
output_variables: ["UP_HELI_MAX_future"] #["UP_HELI_MAX_future"] #["HAIL_MAXK1_future"]
meta_variables: ["masks", "i", "j", "time", "centroid_lon", "centroid_lat",
                 "centroid_i", "centroid_j", "track_id", "track_step", "run_date"]
train_start_date: "2010-10-01"
train_end_date: "2014-12-31"
val_start_date: "2014-01-01"
val_end_date: "2014-12-31"
test_start_date: "2015-01-01"
test_end_date: "2017-06-30"
out_path: "/glade/p/cisl/aiml/ggantos/HWT/mode_cnn_uh_201106_relu/"
classifier: 1
classifier_threshold: 75 #75 #0.04
covariance_scale: 1000
lot_kwargs:
  REFL_COM_curr:
    vmin: 0
    vmax: 80
    cmap: "gist_ncar"

models:
  cnn_20200504_000:
    min_filters: 16
    filter_width: 5
    filter_growth_rate: 2
    pooling_width: 2
    min_data_width: 4
    output_type: "sigmoid"
    pooling: "mean"
    loss: "binary_crossentropy"
    hidden_activation: "relu"
    learning_rate: 0.001
    batch_size: 256
    use_dropout: 1
    dropout_alpha: 0.2
    epochs: 20
    dense_neurons: 9
    l2_alpha: 0.001
    early_stopping: 0
    verbose: 1
